# Generated by Django 5.0.4 on 2024-04-30 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=70)),
                ('cpf', models.CharField(max_length=11)),
                ('contato', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=150)),
                ('flamenguista', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('idLivro', models.BigAutoField(primary_key=True, serialize=False)),
                ('capa', models.ImageField(upload_to='')),
                ('titulo', models.CharField(max_length=70)),
                ('autor', models.CharField(max_length=70)),
                ('editora', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=30)),
                ('ano_ed', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('idVendedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=70)),
                ('cpf', models.CharField(max_length=11)),
                ('contato', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=150)),
                ('pis', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('idItem', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('total', models.IntegerField()),
                ('idLivro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcrud.livros')),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcrud.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('idVenda', models.BigAutoField(primary_key=True, serialize=False)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcrud.cliente')),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcrud.item')),
                ('idVendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcrud.vendedor')),
            ],
        ),
    ]
