# Generated by Django 5.0.4 on 2024-05-01 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcrud', '0002_pedido_idcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='idCliente',
            field=models.ForeignKey(default='2121', on_delete=django.db.models.deletion.CASCADE, to='appcrud.cliente'),
        ),
    ]
