# Generated by Django 5.0.4 on 2024-05-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcrud', '0004_remove_item_idpedido_remove_vendas_idpedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
